package com.company.identity.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.HashSet;
import java.util.Set;

/**
 * Represents a user stored in MongoDB.
 *
 * Important fields:
 *  - username: unique login name
 *  - email: unique email
 *  - passwordHash: encrypted password using BCrypt
 *  - roles: which permissions the user has
 *  - enabled: for deactivating accounts
 *
 * @DBRef means we store references to Role documents.
 * A user can have multiple roles → Set<Role>
 */
@Data
@Document(collection = "users")
public class User {

    @Id
    private String id; // unique ID generated by MongoDB

    private String username;       // chosen by the user
    private String email;          // must be unique
    private String passwordHash;   // encrypted password (never store plain text!)

    private boolean enabled = true;   // used to disable user accounts
    private Instant createdAt = Instant.now(); // timestamp for user creation

    @DBRef
    private Set<Role> roles = new HashSet<>(); // list of user roles
}
